[package]
name = "ray"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99.17"
nalgebra = { version = "0.32.3", features = ["rand"] }
num-traits = "0.2.17"
rand = "0.8.5"

[dev-dependencies]
rstest = "0.18.2"
